# Generated by Django 2.1 on 2018-09-01 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Base')),
                ('name', models.CharField(max_length=32, null=True)),
                ('property', models.CharField(max_length=32, null=True)),
                ('rank', models.CharField(max_length=32, null=True)),
                ('description', models.CharField(max_length=128, null=True)),
            ],
            bases=('base.base',),
        ),
    ]
