# Generated by Django 2.1 on 2018-09-01 08:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='updateTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 1, 8, 58, 31, 516417, tzinfo=utc), null=True),
        ),
    ]
