# Generated by Django 2.1 on 2018-09-05 06:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobModule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodule',
            name='createTime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='jobmodule',
            name='createUser',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='jobmodule',
            name='isDelete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='jobmodule',
            name='status',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='jobmodule',
            name='updateTime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='jobmodule',
            name='updateUser',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
