# Generated by Django 2.1 on 2018-08-23 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0006_auto_20180822_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, null=True)),
                ('context', models.CharField(max_length=1024, null=True)),
                ('createTime', models.DateTimeField(auto_now=True, null=True)),
                ('updateTime', models.DateTimeField(auto_now=True, null=True)),
                ('isDelete', models.BooleanField(default=False, max_length=2)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='library.Author')),
            ],
        ),
    ]
