# Generated by Django 2.1 on 2018-08-24 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0006_auto_20180822_1022'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64, null=True)),
                ('description', models.CharField(max_length=256, null=True)),
                ('isDelete', models.BooleanField(default=False, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, null=True)),
                ('context', models.CharField(max_length=1024, null=True)),
                ('createTime', models.DateTimeField(auto_now=True, null=True)),
                ('updateTime', models.DateTimeField(auto_now=True, null=True)),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='library.Author')),
            ],
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='library.Author'),
        ),
        migrations.AddField(
            model_name='comment',
            name='catalogue',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Catalogue'),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Category'),
        ),
    ]
