# Generated by Django 2.1 on 2018-08-25 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180825_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='library.Author'),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.Category'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='library.Author'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='catalogue',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.Catalogue'),
        ),
    ]
