# Generated by Django 2.1 on 2018-08-25 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180825_0608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='createTime',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updateTime',
        ),
    ]
