# Generated by Django 2.1 on 2018-09-03 11:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createUser', models.CharField(default=None, max_length=32, null=True)),
                ('updateUser', models.CharField(default=None, max_length=32, null=True)),
                ('createTime', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updateTime', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(default=None, max_length=16, null=True)),
                ('isDelete', models.BooleanField(default=False, null=True)),
                ('name', models.CharField(default=None, max_length=32, null=True)),
                ('match', models.IntegerField(default=None, null=True)),
                ('text', models.CharField(default=None, max_length=1024, null=True)),
                ('attachment', models.FileField(default=None, null=True, upload_to='media/attachment')),
                ('user_id', models.IntegerField(default=None, null=True)),
                ('jobInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobInfo.JobInfo')),
            ],
            options={
                'db_table': 'apps_TestReport',
            },
        ),
    ]
